name: Build and Deploy to GCP 

on:
  workflow_dispatch: 
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'vivek-patch-2'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Modules
        run: go mod tidy

      - name: Build
        run: go build .
        path: ./start_build

      
  deploy: 
    name: Deploy to GCP VM
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job completes successfully before deploying
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      # Add Google Cloud authentication steps here
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: bucket-handler@nested-vms-290310.iam.gserviceaccount.com


      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      

      - name: Copy files to GCP VM
        run: scp -r ./start_build/* root@34.100.157.130:/home/azureserver

      - name: Run deployment script on GCP VM
        run: ssh root@34.100.157.130 bash 'cd /home/azureserver && ./start_build'
