name: Build and Deploy to GCP 
on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Modules
        run: go mod tidy

      - name: Build
        run: go build .
        path: ./start_build

      
 
