name: Build and Deploy to GCP

on:
  workflow_dispatch:
    
     
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Modules
        run: go mod tidy

      - name: Build
        run: go build .

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: start_build
          path: ./start_build

  deploy: 
    name: Deploy to GCP VM
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job completes successfully before deploying
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Copy files to GCP VM
        run: scp -r ./start_build/* root@34.100.157.130:/home/azureserver

      - name: Run deployment script on GCP VM
        run: ssh root@34.100.157.130 'cd /home/azureserver && ./start_build'
