name: Build remote-build

on:
  push:
    branches:
      - vivek-patch-2
    
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Modules
        run: go mod tidy

      - name: Build
        run: go build .

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before starting the release job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Release ${{ github.ref }}"
          draft: false
          prerelease: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: .  # You may need to adjust this depending on your project structure
          if-no-files-found: error
