name: My Workflow

on:
  push:
    tags:
      - 'my-manual-trigger'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Modules
        run: go mod tidy
      
      - name: Build
        run: go build -v ./...

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: start_build 
          
